(BugFix) fix #47 #13 - autoconvert some var attr
aodn/python-aodntools pull request #144
Opened 2021-08-03 07:23 UTC by lbesnard

autoconversion of _FillValue, valid_min, valid_max, valid_range as specified in
https://github.com/aodn/python-aodntools/issues/13#issuecomment-432006164

@leonardolaiolo FYI,
under python-aodntools/test_aodntools/ncwriter, to run the new unittests I do the following
```bash
pytest -k 'test_var_attr_'
```

2021-08-04 03:20 UTC, mhidas requested changes
A couple of suggestions to make the tests more complete, and to make sure they pass.

2021-08-04 03:20 UTC, mhidas commented on test_aodntools/ncwriter/test_template.py
> +                    'valid_max': 5,
You're testing the exact same case 4 times (variable is `float32`, attribute looks like integer). How about changing one of the variables to `float64`, and maybe adding an `int32`, and specifying some of these numbers with a decimal point.

Should also test the correct handling of 
* 'valid_range', as it is array-valued (e.g. `'valid_range': [-4, 5]`), and
* '_FillValue', which is a special attribute, handled by the NetCDF4 library.

2021-08-04 03:20 UTC, mhidas commented on aodntools/ncwriter/template.py
> +        varattrs_to_convert_to_datatype = ['_FillValue', 'valid_min', 'valid_max', 'valid_range']
Don't need to include '_FillValue' as it is handled by the NetCDF4 library when it creates the variable.

2021-08-04 03:20 UTC, mhidas commented on aodntools/ncwriter/template.py
> +                    varattr[varattr_to_convert] = np.array(varattr[varattr_to_convert]).astype(varattr['_datatype']).item()
This looks more complicated than it needs to be, and doesn't work for array-valued attributes. This seems to work for me:
```suggestion
                    varattr[varattr_to_convert] = np.array(varattr[varattr_to_convert], dtype=varattr['_datatype'])
```

2021-08-09 00:58 UTC, lbesnard commented
are we all good to merge this ?

2021-08-09 01:12 UTC, mhidas approved these changes
:+1:

2021-08-09 01:17 UTC, merged